# Generated by Django 5.1.4 on 2024-12-08 21:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='Nota del día')),
                ('date', models.DateField(default=django.utils.timezone.now, unique=True, verbose_name='Fecha')),
            ],
        ),
    ]
